version: 2

models:
  - name: fact_trips
    description: ""
    columns:
      - name: trip_id
        data_type: string
        description: ""

      - name: vendor_id
        data_type: int64
        description: ""

      - name: service_type
        data_type: string
        description: ""

      - name: ratecode_id
        data_type: int64
        description: ""

      - name: pickup_location_id
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dropoff_location_id
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""

      - name: payment_type_description
        data_type: string
        description: ""

  - name: dim_zones
    description: ""
    columns:
      - name: location_id
        data_type: numeric
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: zone
        data_type: string
        description: ""

      - name: service_zone
        data_type: string
        description: ""

  - name: dim_montlhy_zone_revenue
    description: ""
    columns:
      - name: revenue_zone
        data_type: string
        description: ""

      - name: revenue_month
        data_type: timestamp
        description: ""

      - name: service_type
        data_type: string
        description: ""

      - name: revenue_monthly_fare
        data_type: numeric
        description: ""

      - name: revenue_monthly_extra
        data_type: numeric
        description: ""

      - name: revenue_monthly_mta_tax
        data_type: numeric
        description: ""

      - name: revenue_monthly_tip_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_tolls_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_improvement_surcharge
        data_type: numeric
        description: ""

      - name: revenue_monthly_total_amount
        data_type: numeric
        description: ""

      - name: total_monthly_trips
        data_type: int64
        description: ""

      - name: avg_monthly_passenger_count
        data_type: float64
        description: ""

      - name: avg_monthly_trip_distance
        data_type: numeric
        description: ""
