services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=marcosbenicio
      - POSTGRES_PASSWORD=0102
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./taxi-trip-postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marcosbenicio@admin.com
      - PGADMIN_DEFAULT_PASSWORD=0102
    ports:
      - "8080:80"
    networks:
      - default
    

networks:
  default:
    external:
      name: pg-network
